# Generated by Django 2.0.6 on 2018-06-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='ans',
            field=models.CharField(default='abss', max_length=200),
        ),
    ]
