# Generated by Django 2.0.6 on 2018-07-02 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_custuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='custuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='CustUser',
        ),
    ]
