# Generated by Django 2.0.6 on 2018-07-04 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_problem_ques_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='max',
            new_name='max_players',
        ),
    ]
