# Generated by Django 2.0.6 on 2018-07-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20180704_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='types',
            field=models.CharField(default='Closed', max_length=100),
        ),
    ]
