# Generated by Django 2.0.6 on 2018-07-06 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_auto_20180706_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='status',
        ),
    ]
