# Generated by Django 2.0.6 on 2018-07-06 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_remove_room_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='types',
            new_name='room_status',
        ),
    ]
