# Generated by Django 2.0.6 on 2018-07-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_auto_20180706_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='ques_num',
            field=models.IntegerField(default=1),
        ),
    ]
