# Generated by Django 2.0.6 on 2018-07-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_auto_20180717_0633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='ans_chosen',
        ),
        migrations.AddField(
            model_name='player',
            name='ans_status',
            field=models.CharField(default='offline', max_length=100000),
        ),
    ]
